use onlinebankingsystem;

CREATE TABLE Clients (ID int(10) NOT NULL AUTO_INCREMENT, firstName varchar(45) NOT NULL, lastName varchar(45) NOT NULL, SSN varchar(11) NOT NULL UNIQUE, dateOfBirth date NOT NULL, address varchar(50) NOT NULL, city varchar(25) NOT NULL, phoneNumber varchar(10) NOT NULL, email varchar(50) NOT NULL UNIQUE, PRIMARY KEY (ID));
CREATE TABLE Accounts (ID int(10) NOT NULL AUTO_INCREMENT, accountNumber varchar(50) NOT NULL UNIQUE, typeOfAccount int(2) NOT NULL, balance decimal(19, 2) NOT NULL, bank_id int(10) NOT NULL, dateOpened date NOT NULL, lastUpdated date NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Transactions (ID int(10) NOT NULL AUTO_INCREMENT, typeOfTransaction int(2) NOT NULL, account_id int(10) NOT NULL, amount decimal(10, 2) NOT NULL, status varchar(10) NOT NULL, `date` date NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Login (ID int(10) NOT NULL, username varchar(25) NOT NULL UNIQUE, password varchar(25) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Loans (ID int(10) NOT NULL AUTO_INCREMENT, account_id int(10) NOT NULL, typeOfLoan int(2) NOT NULL, amount decimal(9, 2) NOT NULL, monthly_payment decimal(9, 2) NOT NULL, `date` date NOT NULL, period int(3) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Bank (ID int(10) NOT NULL AUTO_INCREMENT, name varchar(30) NOT NULL, address varchar(50) NOT NULL, phoneNumber varchar(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Employees (ID int(10) NOT NULL AUTO_INCREMENT, firstName varchar(45) NOT NULL, lastName varchar(45) NOT NULL,SSN varchar(11), dateOfBirth date NOT NULL, address varchar(50) NOT NULL, city varchar(25) NOT NULL, salary decimal(19, 2) NOT NULL, position varchar(25) NOT NULL, email varchar(50) NOT NULL UNIQUE, PRIMARY KEY (ID));
CREATE TABLE Debit_Cards (ID int(10) NOT NULL AUTO_INCREMENT, account_id int(10) NOT NULL, typeOfCard int(2) NOT NULL, number varchar(20) NOT NULL UNIQUE, cvc varchar(3) NOT NULL, expiry_date date NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Credit_Cards (ID int(10) NOT NULL AUTO_INCREMENT, account_id int(10) NOT NULL, typeOfCard int(2) NOT NULL, number varchar(20) NOT NULL UNIQUE, cvc varchar(3) NOT NULL, expiry_date date NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Loan_Types (ID int(2) NOT NULL AUTO_INCREMENT, type varchar(20) NOT NULL, interest_rate decimal(5, 3) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Account_Customers (account_id int(10) NOT NULL, client_id int(10) NOT NULL, PRIMARY KEY (account_id, client_id));
CREATE TABLE Credit_Card_Types (ID int(2) NOT NULL AUTO_INCREMENT, type varchar(20) NOT NULL, min_limit decimal(10, 2) NOT NULL, max_limit decimal(10, 2) NOT NULL, fee decimal(5, 2) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Transaction_Types (ID int(2) NOT NULL AUTO_INCREMENT, type varchar(20) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Bank_Employees (BankID int(10) NOT NULL, EmployeesID int(10) NOT NULL, PRIMARY KEY (BankID, EmployeesID));
CREATE TABLE Debit_Card_Types (ID int(2) NOT NULL AUTO_INCREMENT, type varchar(20) NOT NULL, fee decimal(5, 2) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Account_Type (ID int(2) NOT NULL AUTO_INCREMENT, type varchar(50) NOT NULL, interest_rate decimal(5,3) NOT NULL, fee decimal(5,2) NOT NULL, PRIMARY KEY (ID));
ALTER TABLE Bank_Employees ADD CONSTRAINT FKBank_Emplo972386 FOREIGN KEY (BankID) REFERENCES Bank (ID);
ALTER TABLE Bank_Employees ADD CONSTRAINT FKBank_Emplo752545 FOREIGN KEY (EmployeesID) REFERENCES Employees (ID);
ALTER TABLE Account_Customers ADD CONSTRAINT FKAccountCus260050 FOREIGN KEY (client_id) REFERENCES Clients (ID);
ALTER TABLE Account_Customers ADD CONSTRAINT FKAccountCus721543 FOREIGN KEY (account_id) REFERENCES Accounts (ID);
ALTER TABLE Transactions ADD CONSTRAINT FKTransactio308488 FOREIGN KEY (typeOfTransaction) REFERENCES Transaction_Types (ID);
ALTER TABLE Debit_Cards ADD CONSTRAINT FKDebitCards751351 FOREIGN KEY (typeOfCard) REFERENCES Debit_Card_Types (ID);
ALTER TABLE Transactions ADD CONSTRAINT FKTransactio438389 FOREIGN KEY (account_id) REFERENCES Accounts (ID);
ALTER TABLE Credit_Cards ADD CONSTRAINT FKCreditCard661097 FOREIGN KEY (account_id) REFERENCES Accounts (ID);
ALTER TABLE Debit_Cards ADD CONSTRAINT FKDebitCards969672 FOREIGN KEY (account_id) REFERENCES Accounts (ID);
ALTER TABLE Loans ADD CONSTRAINT FKLoans726981 FOREIGN KEY (account_id) REFERENCES Accounts (ID);
ALTER TABLE Loans ADD CONSTRAINT FKLoans825262 FOREIGN KEY (typeOfLoan) REFERENCES Loan_Types (ID);
ALTER TABLE Employees ADD CONSTRAINT FKEmployees595864 FOREIGN KEY (BankID) REFERENCES Bank (ID);
ALTER TABLE Accounts ADD CONSTRAINT FKAccounts476954 FOREIGN KEY (bank_id) REFERENCES Bank (ID);
ALTER TABLE Login ADD CONSTRAINT FKLogin126777 FOREIGN KEY (ID) REFERENCES Clients (ID);
ALTER TABLE Credit_Cards ADD CONSTRAINT FKCreditCard519268 FOREIGN KEY (typeOfCard) REFERENCES Credit_Card_Types (ID);
ALTER TABLE Accounts ADD CONSTRAINT FKAccounts71552 FOREIGN KEY (typeOfAccount) REFERENCES Account_Type (ID);
